-
  name: "Python Flask Mysql Application Environment"
  hosts: new_ansible_target_4
  tasks:
    - name: Ping Test
      ping:

    - name: downloading and installing mysql-community-release-el7-5.noarch.rpm
      yum:
        name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
        state: present

    - name: installing MySQL from mysql-community
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - mysql-community-server
          - mysql-community-client
          - mysql-community-devel

    - name: Start and enable MySQL Service
      systemd:
        name: mysqld
        state: started
        enabled: yes
    
    - name: Installing epel-release
      yum:
        name: epel-release
        state: present

    - name: Installing python3, python3-pip, python3-devel
      yum: 
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip
        - python3-devel
    
    - name: Installing GCC
      yum:
        name: gcc
        state: present
        
    - name: Installing flask flask-mysql flask_mysqldb
      pip:
        name: "{{ item }}"
        executable: pip3
      with_items:
        - flask
        - flask-mysql
        - flask_mysqldb
        - flask-wtf
        - passlib

    - name: Open Firewall port 8080
      firewalld:
          port: 8080/tcp
          permanent: yes
          state: enabled
          immediate: true




    - name: Install GIT
      yum:
        name: git
        state: present
